### ISSUE TITLE
Web visualizer locally

### ISSUE THREAD

**Issue by mohammadOsama141** [fakhirali/OpenVoiceChat#32]
Is it possible to run the web visualizer locally?

**Comment by fakhirali** [comment]
The issue with running the web app locally is that it requires access to the microphone. Access to the microphone can only be allowed to https websites. To run the web app locally with https follow the following steps:
- Install `mkcert`
- Run `mkcert localhost 127.0.0.1 ::1`
- This will give you two files: `localhost+x-key.pem` `localhost+x.pem`
- Point to these files in the uvicorn run function: 
```python
uvicorn.run(app, host='0.0.0.0', port=8000, 
        ssl_keyfile="localhost+x-key.pem", ssl_certfile="localhost+x.pem")
```
- Then when you access `https://0.0.0.0:8000/` it will give a "Unknown Issuer" warning. You will be able to access the website with https after pressing continue to website or accept the risk and continue.
